// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgAJX3n6-K4uCUWPrWXS4FnTrn3ynJI5I',
    appId: '1:244454967069:web:aaeb524460c328d80a43f4',
    messagingSenderId: '244454967069',
    projectId: 'lern-ce57f',
    authDomain: 'lern-ce57f.firebaseapp.com',
    storageBucket: 'lern-ce57f.firebasestorage.app',
    measurementId: 'G-3PLBGQZ48L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvyU8lKvzWRz_sZc_fd8shql98vQu05OI',
    appId: '1:244454967069:android:b5edef350c44748c0a43f4',
    messagingSenderId: '244454967069',
    projectId: 'lern-ce57f',
    storageBucket: 'lern-ce57f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxoS9b2PQY_I_MJuQdnj14qmatO_Nc-Gw',
    appId: '1:244454967069:ios:8671daefc61402a30a43f4',
    messagingSenderId: '244454967069',
    projectId: 'lern-ce57f',
    storageBucket: 'lern-ce57f.firebasestorage.app',
    iosClientId: '244454967069-ev6rd876e8qluvk9bd3ah98rgkd3b3q5.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalf',
  );

}